---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education

### Columbia University, Mailman School of Public Health     
New York, NY    
*Master of Science in Biostatistics*    
*September 2024 - Present*

### Colby College   
Waterville, ME    
*Bachelor of Arts, Major: Psychology, Minor: Data Science*    
*September 2020 - May 2024*   
**GPA:** 4.04/4.0   
**Awards and Recognition:** Phi Beta Kappa (2024), National Statistics Honor Society: Mu Sigma Rho (2024)

## Skills

**Programming Skills:** Python, Java, R, SQL, SAS, SPSS       
**Statistical Methodologies:** Statistical modeling, Data visualization, Data structuring and algorithms, Descriptive statistics, Hypothesis Testing, Principal Component Analysis

## Professional Experience

### China Asset Management Company Limited    
Nanjing, China    
*Intern Business Analyst*   
*06/2024 - 08/2024*       
- Conducted analysis and interpretation of historical stock and fund markets to support current investment decisions and
market trend expectations, updating new information daily.    
- Utilized tools such as Python and Excel to execute competitive analysis and develop financial models, identifying potential   
investment opportunities and industry trends, and contributing to the creation of detailed reports and presentations for
stakeholders.   
- Collaborated on cross-functional projects with teams from various departments to refine data management processes and
enhance overall operational efficiency on real time market reporting.   
- Led a research initiative with the intern group to examine the operations, characteristics, and regulatory framework of ETF funds, contributing to the formal presentation of findings.       

### Nanjing Municipal Center for Disease Control and Prevention   
Nanjing, China    
*Intern Data Analyst*       
*06/2023 - 09/2023*       
- Participated in the data cleansing of chronic and non-infectious disease records from local district Centers for Disease Control.    
- Assisted in verifying and rectifying anomalies in the mortality cause database, including out-of-range values, missing entries, and logical inconsistencies.   
- Categorized mortality data by cause of death, utilizing custom-built R functions to calculate mortality rate, gender-specific death rate, age-standardized death rate, infant mortality rate, and cause-specific crude death rate.    
- Evolved multiple linear regression models to identify interaction terms that elucidate the relationship between specific causes of death and variables such as age and genetics; Conducted comparative analysis with existing neural network models to identify areas for improvement.    
- Partnered with colleagues from the Department of Acute and Infectious Illness to perform raw predictions of death rates for the upcoming quarter.   

## Research Experience

### Colby College Statistics Department   
Waterville, ME    
*Research Assistant*    
*09/2023 - 05/2024*   
- Established multiple regression models for small area estimation (SAE) using data from the Forest Inventory and Analysis
(FIA) program of the US Forest Service with 428600 observations and 28 variables using R.   
- Studied in-depth the concepts of random hot deck, approximate Bayesian bootstrap (ABB), and k nearest neighbor (kNN)
imputation methods.   
- Contributed to propose a kNN-based approximation to ABB (KBAABB) for generating an artificial population so that to
estimate the actual number of trees in the area.    
- Facilitated in diagnostic checks during the construction of the artificial population.    

### Cognitive Psychology Lab of Colby College   
Waterville, ME    
*Research Assistant*    
*09/2022 – 12/2023*   
**Project 1:** Research on Stabilizing Accessibility of Prior Knowledge Across the Lifespan.     
- Prepared experiment plans with the team and conducted experiments to examine memory performance of cognitively healthy
younger and older adults using behavioral methods.       
- Assisted in identifying the zone of proximal retrieval of marginal knowledge (MK).       
- Collected experimental data, and visualized results using Excel and SPSS.       
- Assisted in assessing the effectiveness of strategies to recover and maintain access to MK across the lifespan.       
- Published research findings and progress of the lab in school’s annual conference.    
**Project 2:** Investigation on Human Memory Mechanism    
- Based on prior studies, make experiment plans to identify whether people are better at rejecting phonologically related words or semantically related words.      
- Studied the role of articulatory suppression during encoding and retention on impacting people’s memory.    
- Examined if the delay of short-term memory into long-term influences people’s rates of mistaking words in phonological
and semantical lists.   
- Encoded raw data, keep updating visual and descriptive phased results.       
- Trained new researchers on study procedures including recruitment, testing on human subjects, and data recording.   









